<a href="https://colab.research.google.com/github/Aldrin-Fanir/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
* A torch.Tensor is a multidimensional matrix containing elements of a single
data type
* Similar to Numpy Arrays but fail of fun things that make them work better on GPU's
* Default data type of float32






In [2]:
import torch
import numpy as np


# Lists

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

my_list1 = [[1, 2, 3], [2, 3, 5]]
my_list1

[[1, 2, 3], [2, 3, 5]]

# Numpy Arrays

In [6]:
np1 = np.random.rand(3,4) #2D 3*4
np1

np.dtype

numpy.dtype

# Tensors

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d
tensor_3d.dtype

torch.float32

# Create a tensor out of numpy array


In [11]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8206, 0.0036, 0.5030, 0.0840],
        [0.4530, 0.8383, 0.4309, 0.9430],
        [0.5779, 0.0325, 0.2118, 0.4195]], dtype=torch.float64)

# Tensor Operation

In [12]:
import torch
import numpy as np

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape and view


In [13]:
my_torch = my_torch.reshape(2,5) #row * column
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Reshape if we don't know the number of items : using -1

In [16]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_torch2 = my_torch2.reshape(5, -1) #number should be the divisor of total number
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [27]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_torch4 = my_torch3.view(2,5) #reshape and view same functionalities
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
my_torch3 = my_torch3.reshape(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
my_torch3[0,1] = 4141 #full column update my_torch[1]
my_torch3

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices

In [32]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Grab a specific item : similar to python slicing

In [36]:
my_torch = my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [37]:
my_torch[ : 1]

tensor([[0, 1]])

Return column

In [42]:
my_torch[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math operation

In [43]:
import torch

In [44]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

# Addition

In [45]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [46]:
torch.add (tensor_a, tensor_b) #addition longhead

tensor([ 6,  8, 10, 12])

# Subtract

In [47]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [48]:
torch.sub(tensor_b, tensor_a) #subtract longhead

tensor([4, 4, 4, 4])

# Multiplication

In [49]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [50]:
torch.mul(tensor_a, tensor_b) #multiplication longhead

tensor([ 5, 12, 21, 32])

# Division

In [51]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [52]:
torch.div(tensor_b, tensor_a) #division longhead

tensor([5.0000, 3.0000, 2.3333, 2.0000])

# Reminder

In [53]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

# Exponents/power

In [56]:
torch.pow(tensor_b,tensor_a)

tensor([   5,   36,  343, 4096])

# Reassignment

In [57]:
tensor_a.add_(tensor_b  )

tensor([ 6,  8, 10, 12])

In [61]:
print(tensor_a)
print(tensor_b)

tensor([ 6,  8, 10, 12])
tensor([5, 6, 7, 8])


In [63]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [64]:
print(tensor_a)
print(tensor_b)

tensor([11, 14, 17, 20])
tensor([5, 6, 7, 8])
