<a href="https://colab.research.google.com/github/Aldrin-Fanir/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
* A torch.Tensor is a multidimensional matrix containing elements of a single
data type
* Similar to Numpy Arrays but fail of fun things that make them work better on GPU's
* Default data type of float32






In [ ]:
import torch
import numpy as np


# Lists

In [ ]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

my_list1 = [[1, 2, 3], [2, 3, 5]]
my_list1

[[1, 2, 3], [2, 3, 5]]

# Numpy Arrays

In [ ]:
np1 = np.random.rand(3,4) #2D 3*4
np1

np.dtype

numpy.dtype

# Tensors

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d
tensor_3d.dtype

torch.float32

# Create a tensor out of numpy array


In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8206, 0.0036, 0.5030, 0.0840],
        [0.4530, 0.8383, 0.4309, 0.9430],
        [0.5779, 0.0325, 0.2118, 0.4195]], dtype=torch.float64)

# Tensor Operation

In [ ]:
import torch
import numpy as np

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape and view


In [ ]:
my_torch = my_torch.reshape(2,5) #row * column
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Reshape if we don't know the number of items : using -1

In [ ]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_torch2 = my_torch2.reshape(5, -1) #number should be the divisor of total number
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5) #reshape and view same functionalities
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = my_torch3.reshape(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3[0,1] = 4141 #full column update my_torch[1]
my_torch3

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Grab a specific item : similar to python slicing

In [ ]:
my_torch = my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch[ : 1]

tensor([[0, 1]])

Return column

In [ ]:
my_torch[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math operation

In [3]:
import torch

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [8]:
d_tensor_a = torch.tensor([[1,2,3,4],[5,6,7,8]])
d_tensor_b = torch.tensor([[3,2,3,4],[5,6,7,8]])

In [20]:
A = torch.arange(24).reshape(2,3,4)       # shape: [2,3,4]
B = torch.ones(2,3,4) * 10

print(A)
print(B)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]],

        [[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]])


# Addition

In [ ]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
d_tensor_a + d_tensor_b

tensor([[ 4,  4,  6,  8],
        [10, 12, 14, 16]])

In [19]:
 A + B

tensor([[[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]],

        [[22., 23., 24., 25.],
         [26., 27., 28., 29.],
         [30., 31., 32., 33.]]])

In [21]:
torch.add (tensor_a, tensor_b) #addition longhead

tensor([ 6,  8, 10, 12])

# Subtract

In [ ]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [10]:
d_tensor_b - d_tensor_a

tensor([[2, 0, 0, 0],
        [0, 0, 0, 0]])

In [22]:
B - A

tensor([[[ 10.,   9.,   8.,   7.],
         [  6.,   5.,   4.,   3.],
         [  2.,   1.,   0.,  -1.]],

        [[ -2.,  -3.,  -4.,  -5.],
         [ -6.,  -7.,  -8.,  -9.],
         [-10., -11., -12., -13.]]])

In [ ]:
torch.sub(tensor_b, tensor_a) #subtract longhead

tensor([4, 4, 4, 4])

# Multiplication

In [ ]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
d_tensor_a * d_tensor_b

tensor([[ 3,  4,  9, 16],
        [25, 36, 49, 64]])

In [25]:
A * B

tensor([[[  0.,  10.,  20.,  30.],
         [ 40.,  50.,  60.,  70.],
         [ 80.,  90., 100., 110.]],

        [[120., 130., 140., 150.],
         [160., 170., 180., 190.],
         [200., 210., 220., 230.]]])

In [ ]:
torch.mul(tensor_a, tensor_b) #multiplication longhead

tensor([ 5, 12, 21, 32])

# Division

In [ ]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
d_tensor_b / d_tensor_a

tensor([[3., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
B / A

tensor([[[    inf, 10.0000,  5.0000,  3.3333],
         [ 2.5000,  2.0000,  1.6667,  1.4286],
         [ 1.2500,  1.1111,  1.0000,  0.9091]],

        [[ 0.8333,  0.7692,  0.7143,  0.6667],
         [ 0.6250,  0.5882,  0.5556,  0.5263],
         [ 0.5000,  0.4762,  0.4545,  0.4348]]])

In [ ]:
torch.div(tensor_b, tensor_a) #division longhead

tensor([5.0000, 3.0000, 2.3333, 2.0000])

# Reminder

In [ ]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
d_tensor_b % d_tensor_a

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

# Exponents/power

In [ ]:
torch.pow(tensor_b,tensor_a)

tensor([   5,   36,  343, 4096])

In [14]:
torch.pow(d_tensor_b, d_tensor_a)

tensor([[       3,        4,       27,      256],
        [    3125,    46656,   823543, 16777216]])

# Reassignment

In [ ]:
tensor_a.add_(tensor_b  )

tensor([ 6,  8, 10, 12])

In [ ]:
print(tensor_a)
print(tensor_b)

tensor([ 6,  8, 10, 12])
tensor([5, 6, 7, 8])


In [ ]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [ ]:
print(tensor_a)
print(tensor_b)

tensor([11, 14, 17, 20])
tensor([5, 6, 7, 8])
